//feature data
export const featureData = [
  {
    image: 'calendar',
    heading: "Organized format",
    text: "Vanbook keeps everything in its right place, so you'll always have what you need when you need it",
  },
  {
    image: 'clock',
    heading: "Free up time",
    text: "Sync with your bank  so your books are always accurate and up to date",
  },
  {
    image: 'cuate2',
    heading: "Claim everything",
    text: "Claim every of your entitlement at  tax time with your expense receipts stored and sorted in Vanbook",
  },
  {
    image: 'group',
    heading: "Deliver instant answers",
    text: "All-in-one accounting platform that helps you balance everything regarding your business finances",
  },
  {
    image: 'cuate',
    heading: "Manage business with reports",
    text: "Measure what matters with Vanbook easy-to-use reports, You can filter, export and drilldown on the data you need.",
  },
  {
    image: 'rafiki',
    heading: "Unlimited support",
    text: "With Vanbook free and unlimited customer support, help is just a click away 24/7",
  },
];

export const reviewerData = [
  {
    image: 'reviewer1',
    name: "Dave Chapman",
    comment: "We needed an accounting software that could handle the complexities of a large institution. Vanbook fit the bill perfectly. It allows us to manage multiple departments, budgets and funding streams with ease. The reporting features are fantastic, giving us the insights we need to make informed financial decisions. Vanbook has saved us time and resources, and we're confident it will continue to do so as we navigate the ever-changing education landscape.",
    role: "Accountant",
    company: "Altair International School",
  },
  {
    image: 'reviewer2',
    name: "Adeola Adeoye",
    comment: "As the external auditor for DeClair's Academy, I've been impressed with their transition to Vanbook. The software's clear organization and audit trail make my job much easier. Vanbook gives me confidence that the district's finances are well-managed. I highly recommend Vanbook to any school looking for a user-friendly and transparent accounting solution.",
    role: "Accountant, DeClair's Academy",
    company: "Finance Consulting firm",
  },
  {
    image: 'reviewer3',
    name: "Oluwakemi Ade",
    comment: "Vanbook has been a game-changer for our small school. Before, managing finances felt overwhelming with spreadsheets and clunky software. Vanbook is intuitive nd user-friendly, allowing our small finance team to stay on top of everything. Plus, it scales with us - we know it can handle our needs as we grow. We highly recommend Vanbook for any school looking for a streamlined accounting solution!",
    role: "Principal, Wilmer's Academy",
    company: "Institute for higher learning",
  },
  {
    image: 'reviewer1',
    name: "Dave Chapman",
    comment: "We needed an accounting software that could handle the complexities of a large institution. Vanbook fit the bill perfectly. It allows us to manage multiple departments, budgets and funding streams with ease. The reporting features are fantastic, giving us the insights we need to make informed financial decisions. Vanbook has saved us time and resources, and we're confident it will continue to do so as we navigate the ever-changing education landscape.",
    role: "Accountant",
    company: "Altair International School",
  },
  {
    image: 'reviewer2',
    name: "Adeola Adeoye",
    comment: "As the external auditor for DeClair's Academy, I've been impressed with their transition to Vanbook. The software's clear organization and audit trail make my job much easier. Vanbook gives me confidence that the district's finances are well-managed. I highly recommend Vanbook to any school looking for a user-friendly and transparent accounting solution.",
    role: "Accountant, Altair",
    company: "Finance Consulting firm.",
  },
  {
    image: 'reviewer3',
    name: "Oluwakemi Ade",
    comment: "Vanbook has been a game-changer for our small school. Before, managing finances felt overwhelming with spreadsheets and clunky software. Vanbook is intuitive nd user-friendly, allowing our small finance team to stay on top of everything. Plus, it scales with us - we know it can handle our needs as we grow. We highly recommend Vanbook for any school looking for a streamlined accounting solution!",
    role: "Accountant, Altair",
    company: "Institute for higher learning",
  },
];

export const insightsData = [
  {
      figure: "4000+",
      details: "Global customers",
      text: "We are passionate to help over 4,000 amazing global companies."
  },
  {
      figure: "600%",
      details: "Return on investment",
      text: "Our customers should expect an average of ~600% ROI."
  },
  {
      figure: "10k",
      details: "Global downloads",
      text: "Our app has been downloaded over 10k times."
  },
  {
      figure: "200+",
      details: "5-star reviews",
      text: "We’re proud of our 5-star rating with over 200 reviews."
  },
]

export const employeesInfo = [
  {
    name: "John Doe",
    role: "Software Developer",
    phone: "08012345678",
    address: "9 wakam street, Lagos",
    status: "full-time",
    department: "Engineering",
    subject: "Software Development",
    grade: "A",
    step: "1",
    salary: "200,000",
    id: 1,
    dob: '06/12/1998',
    email: 'johndoe@gmail.com',
    gender: 'Female'
  },
  {
    name: "John Doe",
    role: "Software Developer",
    phone: "08012345678",
    address: "9 wakam street, Lagos",
    status: "full-time",
    department: "Engineering",
    subject: "Software Development",
    grade: "A",
    step: "1",
    salary: "200,000",
    id: 2,
    dob: '06/12/1998',
    email: 'johndoe@gmail.com',
    gender: 'Female'
  },
  {
    name: "John Doe",
    role: "Software Developer",
    phone: "08012345678",
    address: "9 wakam street, Lagos",
    status: "full-time",
    department: "Engineering",
    subject: "Software Development",
    grade: "A",
    step: "1",
    salary: "200,000",
    id: 3,
    dob: '06/12/1998',
    email: 'johndoe@gmail.com',
    gender: 'Female'
  },
  {
    name: "John Doe",
    role: "Software Developer",
    phone: "08012345678",
    address: "9 wakam street, Lagos",
    status: "full-time",
    department: "Engineering",
    subject: "Software Development",
    grade: "A",
    step: "1",
    salary: "200,000",
    id: 4,
    dob: '06/12/1998',
    email: 'johndoe@gmail.com',
    gender: 'Female'
  },
  {
    name: "John Doe",
    role: "Software Developer",
    phone: "08012345678",
    address: "9 wakam street, Lagos",
    status: "full-time",
    department: "Engineering",
    subject: "Software Development",
    grade: "A",
    step: "1",
    salary: "200,000",
    id: 5,
    dob: '06/12/1998',
    email: 'johndoe@gmail.com',
    gender: 'Female'
  },
  {
    name: "John Doe",
    role: "Software Developer",
    phone: "08012345678",
    address: "9 wakam street, Lagos",
    status: "full-time",
    department: "Engineering",
    subject: "Software Development",
    grade: "A",
    step: "1",
    salary: "200,000",
    id: 6,
    dob: '06/12/1998',
    email: 'johndoe@gmail.com',
    gender: 'Female'
  },
  {
    name: "John Doe",
    role: "Software Developer",
    phone: "08012345678",
    address: "9 wakam street, Lagos",
    status: "full-time",
    department: "Engineering",
    subject: "Software Development",
    grade: "A",
    step: "1",
    salary: "200,000",
    id: 7,
    dob: '06/12/1998',
    email: 'johndoe@gmail.com',
    gender: 'Female'
  },
]

export const userData = [
  {
    id: 1,
    name: "John Doe",
    lastLogin: "12/12/2021",
    email: "abc@xyz.com",
    dateCreated: "12/12/2021",
    createdBy: "Manny Dev",
    dateActivated: "12/12/2021",
    accesslevel: "Full access",
  },
  {
    id: 2,
    name: "John Doe",
    lastLogin: "12/12/2021",
    email: "abc@xyz.com",
    dateCreated: "12/12/2021",
    createdBy: "Manny Dev",
    dateActivated: "12/12/2021",
    accesslevel: "Budget",
  },
  {
    id: 3,
    name: "John Doe",
    lastLogin: "12/12/2021",
    email: "abc@xyz.com",
    dateCreated: "12/12/2021",
    createdBy: "Manny Dev",
    dateActivated: "12/12/2021",
    accesslevel: "Business overview",
  },
  {
    id: 4,
    name: "John Doe",
    lastLogin: "12/12/2021",
    email: "abc@xyz.com",
    dateCreated: "12/12/2021",
    createdBy: "Manny Dev",
    dateActivated: "12/12/2021",
    accesslevel: "Business overview",
  },
  {
    id: 5,
    name: "John Doe",
    lastLogin: "12/12/2021",
    email: "abc@xyz.com",
    dateCreated: "12/12/2021",
    createdBy: "Manny Dev",
    dateActivated: "12/12/2021",
    accesslevel: "Full access",
  },
  {
    id: 6,
    name: "John Doe",
    lastLogin: "12/12/2021",
    email: "abc@xyz.com",
    dateCreated: "12/12/2021",
    createdBy: "Manny Dev",
    dateActivated: "12/12/2021",
    accesslevel: "Budget",
  },
  {
    id: 7,
    name: "John Doe",
    lastLogin: "12/12/2021",
    email: "abc@xyz.com",
    dateCreated: "12/12/2021",
    createdBy: "Manny Dev",
    dateActivated: "12/12/2021",
    accesslevel: "Sales & expense",
  },
]